#github actions to deploy api

name: Deploy API

on:
  push:
   branches:
     - main
  # workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore ./AspWebApi.csproj

      - name: Build project
        run: dotnet build ./AspWebApi.csproj --no-restore --configuration Release

      - name: Run tests
        run: dotnet test ./AspWebApi.csproj --no-restore --configuration Release

      #Publish project
      - name: Publish project
        run: dotnet publish ./AspWebApi.csproj --configuration Release --output ./publish

      #Deploy project
      - name: Deploy project
        run: dotnet publish ./AspWebApi.csproj --configuration Release --output ./publish

    